{% set name = "mathutils" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mathutils-{{ version }}.tar.gz
  sha256: b9371af8149f3f3f05ee165cb583b2df7b3fbc9935406d1c505a5276b8e563af

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<310]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - setuptools
    - pip
  host:
    - python
  run:
    - python

test:
  imports:
    - mathutils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/ideasman42/blender-mathutils
  summary: A general math utilities library providing Matrix, Vector, Quaternion, Euler and Color classes, written in C for speed.
  license: NGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Krande
